### PR TITLE
grow to 20.0.0

### PR DESCRIPTION
**Pull request by hugovk**
Time for a new release?

19.0.0 was in February.

### CODE REVIEW

**Review by ofek — APPROVED** [review]

**Comment by hugovk** [comment]
@ofek Please could you release to PyPI at some point?

**Comment by ofek** [comment]
```
Uploading distributions to https://upload.pypi.org/legacy/                                                                                                                                                                                                    
  C:\Users\ofek\Desktop\code\pypinfo\dist\pypinfo-20.0.0-py3-none-any.whl (14.6 KB)                                                                                                                                                                           
  C:\Users\ofek\Desktop\code\pypinfo\dist\pypinfo-20.0.0.tar.gz (18.5 KB)                                                                                                                                                                                     
Uploading pypinfo-20.0.0-py3-none-any.whl                                                                                                                                                                                                                     
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34.0k/34.0k [00:00<00:00, 47.8kB/s] 
Content received from server:                                                                                                                                                                                                                                 
<html>                                                                                                                                                                                                                                                        
 <head>                                                                                                                                                                                                                                                       
  <title>400 The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.</title>                                                                                    
 </head>                                                                                                                                                                                                                                                      
 <body>                                                                                                                                                                                                                                                       
  <h1>400 The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.</h1>                                                                                          
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>                                                                                                                                                 
The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.                                                                                                         
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                              
 </body>                                                                                                                                                                                                                                                      
</html>                                                                                                                                                                                                                                                       
```

**Comment by ofek** [comment]
BTW I can add a token to CI, just lmk the desired name of secret

**Comment by hugovk** [comment]
Hmm, I'll check that tomorrow.

A token would be great, we can then use https://github.com/pypa/gh-action-pypi-publish. Their suggested `PYPI_API_TOKEN` would be a good name.

**Comment by ofek** [comment]
Added!

**Comment by hugovk** [comment]
Thanks! https://github.com/ofek/pypinfo/pull/130 should fix the PyPI 400 error.

---

I normally use something like this to auto-deploy:

It does two things.

1. On merges to `master`/`main`, it deploys to Test PyPI.

2. On published releases, it deploys to production PyPI.

https://github.com/isodate/isodate/blob/main/.github/workflows/deploy.yml

A published release is a "GitHub release", when you go to https://github.com/ofek/pypinfo/releases/tag/19.0.0 and "Create release from tag". We can simplify it and have it deploy to prod for tags instead?

So a release would involve something like:

```sh
# Update README release notes and version number as usual and then:
git tag 20.0.0
git push --tags
```

We can also skip the Test PyPI deploy too, although it's nice to know the release machinery is running smoothly before release day.

What do you think?

**Comment by ofek** [comment]
Sounds great!

**Pull request merged**
