### PR TITLE
Prepare release 22.0.0

### PR DESCRIPTION
**Pull request by hugovk**
The last release was a while ago on 2022-06-13, let's make a new one as requested in https://github.com/ofek/pypinfo/commit/7a1c53ca76d747ab50e8adbbb1ec82394f989a27.

### CODE REVIEW

**Review by ofek — APPROVED** [review]
Thank you!

**Comment by hugovk** [comment]
Please could you upload to PyPI?

**Comment by ofek** [comment]
Are you allowed to push tags? https://github.com/ofek/pypinfo/blob/master/.github/workflows/deploy.yml

**Comment by hugovk** [comment]
Oh yes, I can :)

Released! 🚀 

* https://github.com/ofek/pypinfo/actions/runs/10541535753/job/29207386123

* https://pypi.org/project/pypinfo/22.0.0/

**Comment by ofek** [comment]
Awesome just wanted to make sure, thanks!

**Pull request merged**
