### PR TITLE
Document and test support for Python 3.9 official release

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Review by ofek — APPROVED** [review]
🥇

**Comment by ofek** [comment]
Oop need rebase

**Comment by jdufresne** [comment]
Rebased

**Review by ofek — APPROVED** [review]

**Comment by hugovk** [comment]
Any idea why the 3.9 + Windows job is failing? Maybe missing Cython wheels?

https://github.com/ofek/pypinfo/runs/1338829495

**Comment by hugovk** [comment]
Or maybe grpc: https://github.com/grpc/grpc/issues/24344

**Comment by jdufresne** [comment]
@hugovk That looks to be the issue to me. Should we pull Python 3.9 testing until that is resolved or do you think it is worth keeping?

**Comment by hugovk** [comment]
We could probably just exclude 3.9 + Windows for now and keep the other 3.9s?

---

PyPy3 has also started failing on Travis CI, we can see the monthly cron failed with no changes here:

* https://travis-ci.com/github/ofek/pypinfo/builds
* Last pass 2 months ago: https://travis-ci.com/github/ofek/pypinfo/jobs/381232499
* First fail 28 days ago: https://travis-ci.com/github/ofek/pypinfo/jobs/394809163

Also looks like grpcio.

**Comment by hugovk** [comment]
Follow up: grpc wheels are out for Windows (https://github.com/grpc/grpc/issues/24344#issuecomment-725303543) and now passing for 3.9 + Windows:

* https://github.com/hugovk/pypinfo/runs/1384523805?check_suite_focus=true

**Comment by jdufresne** [comment]
Thanks @hugovk

**Pull request merged**
