### PR TITLE
Add support for version matching

### PR DESCRIPTION
**Pull request by mayeut**
This allows to gather statistics on specific version of a project.
This implements [PEP 440 version matching](https://peps.python.org/pep-0440/#version-matching).

e.g.

With an exact version:
```
pypinfo % pypinfo 'numpy==1.22.4' file
Served from cache: False
Data processed: 37.83 MiB
Data billed: 38.00 MiB
Estimated cost: $0.01

| file                                                                    | download_count |
| ----------------------------------------------------------------------- | -------------- |
| numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |          9,291 |
| numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |          2,379 |
| numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl |            962 |
| numpy-1.22.4.zip                                                        |            572 |
| numpy-1.22.4-cp310-cp310-win_amd64.whl                                  |            371 |
| numpy-1.22.4-cp39-cp39-win_amd64.whl                                    |            311 |
| numpy-1.22.4-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl |            153 |
| numpy-1.22.4-cp38-cp38-win_amd64.whl                                    |            135 |
| numpy-1.22.4-cp39-cp39-macosx_10_15_x86_64.whl                          |             80 |
| numpy-1.22.4-cp38-cp38-macosx_10_15_x86_64.whl                          |             74 |
| Total                                                                   |         14,328 |
```

Or with prefix matching:
```

pypinfo % pypinfo  'numpy==1.23.*' file
Served from cache: False
Data processed: 37.83 MiB
Data billed: 38.00 MiB
Estimated cost: $0.01

| file                                                                       | download_count |
| -------------------------------------------------------------------------- | -------------- |
| numpy-1.23.0rc3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |             12 |
| numpy-1.23.0rc3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |              9 |
| numpy-1.23.0rc3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl |              5 |
| numpy-1.23.0rc2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |              4 |
| numpy-1.23.0rc2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |              3 |
| numpy-1.23.0rc3-cp38-cp38-macosx_11_0_arm64.whl                            |              2 |
| numpy-1.23.0rc3-cp310-cp310-win_amd64.whl                                  |              2 |
| numpy-1.23.0rc2.tar.gz                                                     |              1 |
| numpy-1.23.0rc2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl |              1 |
| Total                                                                      |             39 |
```

### CODE REVIEW

**Review by ofek — APPROVED** [review]
LGTM! I'll let @hugovk take a look

**Review by hugovk — COMMENTED** [review]
Not a huge fan of big regexes but this will be very useful: often we're interested only in stats for the newer releases (e.g. can we drop old Python versions or old manylinux/32-bit wheels).

Please could you add some examples to the README?

Thanks!

**Comment by mayeut** [comment]
> Not a huge fan of big regexes but this will be very useful: often we're interested only in stats for the newer releases (e.g. can we drop old Python versions or old manylinux/32-bit wheels).

I don't like the complexity of these big regexes either but, as you mentioned, the pros outweigh the cons. Unfortunately versions are not normalized in the big query tables which would have helped reducing the complexity (but it's understandable given it would not "string" match the valid PEP440 version in metadata).

> Please could you add some examples to the README?

Will do. I'll also add some tests showing the regex are doing what they're supposed to.

**Comment by mayeut** [comment]
> Please could you add some examples to the README?

I updated the README with 2 examples in 1 section. This does not follow other examples but I felt it was really related to 1 feature. Let me know if it needs splitting.

I also added some tests (and found 1 issue regarding `epoch` while doing so which is now fixed)

**Comment by mayeut** [comment]
I'll rebase to fix the conflict.

**Review by ofek — APPROVED** [review]

**Pull request merged**
