### PR TITLE
Change --order argument parsing to use the fields from FIELD_MAP as named in "pypinfo --help"

### PR DESCRIPTION
**Pull request by bskinn**
Previously, the field names passed to `order` had to be those of the actual BigQuery database, and not those displayed with `pypinfo --help`. Now the appropriate field substitution is made when the `order` argument is passed into `build_query`.

### CODE REVIEW

**Comment by ofek** [comment]
I haven't tested but I trust you have :)

**Comment by bskinn** [comment]
I've hand-tested a couple of cases, but did not run tox. My Windows boxes are poorly set up for it. The change works for `date`, `month`, and `year` at least, and works correctly if no `-o`arg is passed. I can clone to my Linux box if you'd like me to test it fully.

**Comment by ofek** [comment]
No, we ONLY hand test. Otherwise, I'd be broke :) Thanks again!

**Comment by bskinn** [comment]
Hehe, fair enough. :-) Happy to help!

**Pull request merged**
